### ISSUE TITLE
Some explanation

### ISSUE THREAD

**Issue by mikicho** [DoclerLabs/hexMachina-HelloWorld#4]
Hey,
I wanna start to work with hexMachina, can you please write some words and connect the ideological side, that explained in the hexMachina site, to the practical side that write in this project?
Thanks,
Michael

**Comment by aliokan** [comment]
I have made some refactoring in project to follow the latest usage, and description in [README](https://github.com/DoclerLabs/hexMachina-HelloWorld/blob/master/README.md). 

feel free to ask more detail if something is not clear

have fun!
