### ISSUE TITLE
Error: Multiple targets

### ISSUE THREAD

**Issue by mikicho** [DoclerLabs/hexMachina-HelloWorld#5]
Hey,
I have haxe 3.4.2 and when I tried to compile the hello world project: `haxe build/build.hxml -js bin/HelloWorld.js` I got: `Error: Multiple targets`

**Comment by aliokan** [comment]
fixed by DoclerLabs/hexMachina-HelloWorld@d935e36f99bccef95f35728f352c4402c802d719
